FROM oven/bun:1.1.0-alpine AS base

# Install dependencies
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

# Copy source code
COPY . .

# Build the application
RUN bun run build

# Expose port
EXPOSE 3100

# Start the application
CMD ["bun", "dist/bin/server.js"]
