services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cqrs_demo_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app-network

  # User Service
  service-user:
    build:
      context: ../../service-user
      dockerfile: Dockerfile.dev
    container_name: service-user-dev
    environment:
      NODE_ENV: dev
      DB_URL: postgresql://postgres:postgres@postgres:5432/cqrs_demo_dev
      JWT_SECRET: supersecret-change-me-in-production
      USER_SERVICE_PORT: 3101
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3101:3101"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # Product Service
  service-product:
    build:
      context: ../../service-product
      dockerfile: Dockerfile.dev
    container_name: service-product-dev
    environment:
      NODE_ENV: dev
      DB_URL: postgresql://postgres:postgres@postgres:5432/cqrs_demo_dev
      PRODUCT_SERVICE_PORT: 3102
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3102:3102"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # Auth Service
  service-auth:
    build:
      context: ../../service-auth
      dockerfile: Dockerfile.dev
    container_name: service-auth-dev
    environment:
      NODE_ENV: dev
      JWT_SECRET: supersecret-change-me-in-production
      AUTH_SERVICE_PORT: 3100
      PORT: 3100
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3100:3100"
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    networks:
      - app-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  app-network:
    driver: bridge
