services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres-staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cqrs_demo_staging
    ports:
      - "5432:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - app-network

  # User Service
  service-user:
    image: bun-hono-redis-cqrs/service-user:staging
    container_name: service-user-staging
    environment:
      NODE_ENV: staging
      DB_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/cqrs_demo_staging
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_PORT: 3101
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3101:3101"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # Product Service
  service-product:
    image: bun-hono-redis-cqrs/service-product:staging
    container_name: service-product-staging
    environment:
      NODE_ENV: staging
      DB_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/cqrs_demo_staging
      PRODUCT_SERVICE_PORT: 3102
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3102:3102"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # Auth Service
  service-auth:
    image: bun-hono-redis-cqrs/service-auth:staging
    container_name: service-auth-staging
    environment:
      NODE_ENV: staging
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SERVICE_PORT: 3100
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3100:3100"
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: redis-staging
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_staging_data:/data
    networks:
      - app-network

volumes:
  postgres_staging_data:
  redis_staging_data:

networks:
  app-network:
    driver: bridge
