services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6380:6379"
    # Disable AOF and RDB for maximum performance in development
    command: redis-server --appendonly no --save ""
    volumes:
      - redis_data:/data
    networks:
      - redis-network

volumes:
  redis_data:
    driver: local

networks:
  redis-network:
    driver: bridge
